# Run the published build docker image using file system web resources
# Usage:
# $ docker compose --file ./docker-compose-published.yml build --no-cache --pull
# $ docker compose --file ./docker-compose-published.yml up --force-recreate --detach
# $ docker compose --file ./docker-compose-published.yml logs --tail="all" --follow
# $ docker compose --file ./docker-compose-published.yml down --remove-orphans
# Browse: curl --head http://localhost:8081/home.html
version: '3.8'

services:

  catalogue:
    image: ghcr.io/antonycc/diy-accounting:main
    networks:
      - app
  content:
    image: ghcr.io/antonycc/diy-accounting-mdcms:main
    networks:
      - app
  web:
    image: ghcr.io/antonycc/diyaccounting-web:main
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - app
      - admin
      - public
  http:
    depends_on:
      - web
    links:
      - web
    build:
      context: docker/http
    ports:
      - 8081:80
    volumes:
      - ./src/main/webapp:/usr/share/webapp:ro
    networks:
      - app
      - public

networks:
  admin:
    driver: bridge
  app:
    driver: bridge
  public:
    driver: bridge
