FROM nginx

MAINTAINER DIY Accounting https://diyaccounting.co.uk/

# Uncomment to place static HTML in nginx doc root in Docker: http://localhost:8081/index.html
#COPY ./index.html /usr/share/webapp

COPY nginx.conf /etc/nginx/nginx.conf
